# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bb44f1e46e28651f02d16ba059facf579b3c52f9bfb9c8e592a7638d7f3441f98d3e89b882aef67d3919863f7cf5753a54a9d26987c23ac06d49661d271710a

test:
  secret_key_base: cfc225547fb1f4e0cab9b75c372497f05b55e4c2c69e28806b1641b68bf9c9696027df44f5f92b206a2e59a2b6995486768f55915900c070a3f920964f9e2cb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
